id: I369A81D2
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:15:38.810953
last_modified: 2023-02-08 15:15:38.811037
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: zh
bases:
  '3539':
    base_file: 3539.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
